### ISSUE TITLE
How did you avoid `lazy-lock.json` issue in your neovim config?

### ISSUE THREAD

**Issue by Nikola-Milovic** [woutdp/nixos-config#1]
Hey! I stumbled upon your dotfiles from reddit, and I saw that you mentioned not having issues with `lazy-lock.json`. Reading your config I don't see why the `lazy-lock.json` file wouldn't cause issues, you didn't disable it in any way?

Can you please provide me with a brief explanation of what your config does exactly to mitigate the issue of the lock file being copied over and used on a read-only filesystem.

**Comment by woutdp** [comment]
I don't have a `lazy-lock.json` file in my setup: https://github.com/woutdp/nixos-config/tree/master/home/neovim/nvim

So it doesn't get copied over. Originally that wasn't the case and it did cause issues. Maybe I'm misunderstanding please let me know

**Comment by Nikola-Milovic** [comment]
But doesn't lazy write the lock file everytime you install/ update something regardless?

**Comment by woutdp** [comment]
Yes but since it's not copied over it's not in read-only mode, it's allowed to be overwritten. I could be wrong here again please correct me, but it seems to be working for me. When looking at the lock file I don't have any read-only permissions or symlinking or anything like that, it's just a regular file that lazyvim can overwrite.

**Comment by Nikola-Milovic** [comment]
Thanks! I think I'll try something like this
